### ISSUE TITLE
"JSON input" validation

### ISSUE THREAD

**Issue by paluh** [paluh/purescript-polyform#1]
Request originaly posted on slack by @thomashoneyman:

1. We have a form that either gets instantiated with default values, or should be parsed from JSON.
2. For each field, we want to run a list of validation rules against the value of the field on a blur event
3. On submit, we want to ensure every field is valid and, in some cases, do another full pass over the fields
4. We want to serialize the validated form to JSON and send it back off to the database.

Fairly standard round-trip, but building up the form has involved an obscene level of duplication so far. We’re going to need to support dynamic forms in the future, so we want fields to carry their validation / display information themselves and be composable into one larger form.

**Comment by thomashoneyman** [comment]
Another view:

```
Server -----> 
  Maybe JSON -> Raw Form -> Valid Form -> JSON 
------> Server
```

With a minimal amount of boilerplate. One approach is that of `formlets`. Curious to see an example of this with Polyform as well!

**Comment by paluh** [comment]
I'm not sure if this meets your requirements:

https://github.com/paluh/purescript-polyform/blob/master/src/Polyform/Input/Foreign.purs

I hope I will implement some tests soon to show how it works..

**Comment by paluh** [comment]
Regarding pure validation process bidirectional json validation is currently handled by contrib lib:

https://github.com/lambdaterms/purescript-polyform-validators/blob/master/test/Duals/Validators/Json.purs#L47

Please check also short write up in the README.
